FROM python
COPY ./static /home/devasc/CPE41S1/designprojapp/static/
COPY ./templates /home/devasc/CPE41S1/designprojapp/templates/
COPY design_app.py /home/devasc/CPE41S1/designprojapp
EXPOSE 5050
CMD python3 /home/devasc/CPE41S1/sample-app/login.py
